import { defineConfig } from "tsdown";

const jsExtensions = () => ({ js: ".js", dts: ".d.ts" });

export default defineConfig([
	{
		entry: { "shared/index": "src/shared/index.ts" },
		format: "esm",
		outDir: "dist",
		dts: true,
		clean: true,
		platform: "node",
		external: [/^convex/],
		outExtensions: jsExtensions,
	},
	{
		entry: { "client/index": "src/client/index.ts" },
		format: "esm",
		outDir: "dist",
		dts: true,
		clean: false,
		platform: "browser",
		shims: true,
		external: [/^convex/, "@logtape/logtape", "effect", "@effect/platform"],
		outExtensions: jsExtensions,
	},
	{
		entry: { "server/index": "src/server/index.ts" },
		format: "esm",
		outDir: "dist",
		dts: true,
		clean: false,
		platform: "node",
		external: [
			/^convex/,
			"effect",
			"@effect/platform",
			"@logtape/logtape",
			"jose",
		],
		outExtensions: jsExtensions,
	},
	{
		entry: { "executor/index": "src/server/executor-entry.ts" },
		format: "esm",
		outDir: "dist",
		dts: true,
		clean: false,
		platform: "node",
		external: [
			/^convex/,
			"@browserbasehq/stagehand",
			"effect",
			"@effect/platform",
			"@logtape/logtape",
		],
		outExtensions: jsExtensions,
	},
	{
		entry: { "handler/index": "src/handler/index.ts" },
		format: "esm",
		outDir: "dist",
		dts: true,
		clean: false,
		platform: "node",
		external: [
			/^convex/,
			"@browserbasehq/stagehand",
			"effect",
			"@effect/platform",
			"@logtape/logtape",
			"jose",
		],
		outExtensions: jsExtensions,
	},
	{
		entry: ["src/component/**/*.ts"],
		format: "esm",
		outDir: "dist/component",
		dts: true,
		clean: false,
		unbundle: true,
		platform: "node",
		external: [/^convex/, "@logtape/logtape"],
		outExtensions: jsExtensions,
	},
]);
